### ISSUE TITLE
Robot always turns clockwise even when counterclockwise is faster/shorter

### ISSUE THREAD

**Issue by PeterMitrano** [StanleyInnovation/vector_v1#12]
Running the 2d_map_nav configuration:
If the robot is given a goal the is behind it, but more than 90 degrees counterclockwise, it turns the farther angle and goes clockwise. I'm not sure why this is. I have set `min_rot_vel` to `-0.5`.

*update* so it's not exactly 90 deg. it's more like 45deg. 

Example:

![demo](https://cloud.githubusercontent.com/assets/4010770/16536222/122c119e-3fbd-11e6-8638-3482364abead.png)

**Comment by PatrickHussey** [comment]
This is likely an artifact of the dwa planner and setting penalize negative motion parameter to true. 

There are atleast 2 ways around it:

1. Add a second rear facing laser and adjust the planner parameters to be able to move in all directions (this is what we generally do)

2. Try TrajectoryPlannerROS with dwa set to false, or some other local planner

**Comment by PeterMitrano** [comment]
yea I figured out that is was DWA's fault, but I didn't get to the root cause, so thanks for that info. I've actually switch to an entirely new planner (eband) which does much better in most cases.

**Comment by PatrickHussey** [comment]
Yeah I have found DWA to work reasonably well for differential platforms with relatively low computational horsepower. E-Band is a good choice, I have wanted to test this for a while:

http://wiki.ros.org/teb_local_planner

it seems to have some advantages over the eband_local_planner based on reasding through the paper.

**Comment by PatrickHussey** [comment]
Also noticed you have min_rot_vel set to a negative number. It should be positive based on the definition:

"The absolute value of the minimum rotational velocity for the robot in rad/s"

Also playing with that value and the min_trans_vel will affect the behavior you were talking about. Note that the DWA cannot plan to turn in place it always plans an arc.
