### ISSUE TITLE
Quick Start Guide is Missing

### ISSUE THREAD

**Issue by cjds** [StanleyInnovation/vector_v1#26]
The quick start guide is missing from the wiki (and links to it are broken). It would be useful to have for anyone who's getting started with this in the future. 

In case it's missing completely here's a link to it on Google Drive

https://drive.google.com/file/d/0B77UzQX3CxDiRUh5NkJUNEYxMHc/view

**Comment by PatrickHussey** [comment]
The quick start guide is still in the repo:

[https://github.com/StanleyInnovation/vector_v1/blob/master/vector_embedded_firmware/Vector%20Quick%20Start%20Guide.pdf](url)

not sure why the wiki link is broken though

**Comment by cjds** [comment]
The one in the Wiki is pointing to the `hlpr_merge` branch instead of the master.
