### ISSUE TITLE
experimental gain tuning branch problems

### ISSUE THREAD

**Issue by athomaz** [StanleyInnovation/vector_v1#27]
We are trying to get the experimental gain tuning branch to run and here are the biggest problems so far: 

vchk gives the error: 
Timed out waiting for Vector feedback topics make sure the driver is running

This is due to the fact that vector_driver inside vector_ros with the error: 
Could not start VECTOR communication stream

Then we debugged this down to a line in vector_comm.py inside vector_ros, line 307: 
elif (len(rsp_data) == NUMBER_OF_VECTOR_RSP_WORDS):

the rsp_data is giving 110 and the NUMBER_OF_VECTOR_RSP_WORDS is expecting 121

And that is as far as we got. Please advise.

**Comment by PatrickHussey** [comment]
You probably just need to update the embedded firmware. There were some significant changes in the communication protocol to support on the fly gain updates.

**Comment by vchu** [comment]
Ah thanks for the pointer. We missed that it required a firmware update.

On a side note - can you point us to where the numbers for the two different gains sets are stored? we can't seem to find a file that has the one with the tile floor (UT) vs the carpet (GT)

**Comment by PatrickHussey** [comment]
The config for the platform that gets loaded at startup is located here:

[vector_params.yaml](https://github.com/StanleyInnovation/vector_v1/blob/experimental_gain_tuning/vector_robot/vector_bringup/launch/platform/config/vector_params.yaml)

It only has the one gain set though, I will add something that has both for reference when I get a chance

**Comment by vchu** [comment]
Good to know. What gainset is that currently for? tile floor or carpet?

**Comment by athomaz** [comment]
We are going to start tuning for carpet in about an hour (2pm EST), so any pointers you have about what gains the GT robot uses would be much appreciated...  Otherwise we'll just have to start changing things slowly.

**Comment by PatrickHussey** [comment]
So the gains for the release you have should work on carpet and hard floors. Its somewhat in the middle.

The gainsets I have from development:

1. -----------------------------
p: 1.0
i: 0.8
d: 0.0
fdfwd: 1.0
------------------------------
That is the first one from hard floors

2. -----------------------------
p: 1.6
i: 1.4
d: 0.0
fdfwd: 1.0
------------------------------
Works on hardfloors and low pile carpet well. Not stiff enough for high pile carpet

3. -----------------------------
p: 1.8
i: 1.58
d: 0.0
fdfwd: 1.0
------------------------------
Works on most flooring might oscillate slightly on really smooth floors in straffe

4. -----------------------------
p: 2.3
i: 2.6
d: 0.0
fdfwd: 1.0
------------------------------
The one Sonia has for heavy pile carpeting

There are alot of nobs to play with to improve behavior, but needs to be done empirically on the actual surface. Somewhere between 2 and 3 with some work on the limits and drain rates should work for almost all surfaces.

**Comment by vchu** [comment]
Thanks! These were super helpful

**Comment by athomaz** [comment]
Thanks Patrick, we were able to get things working and are planning to merge the experimental gain tuning into the main branch soon.
