### ISSUE TITLE
vector_comm.py _update_move_base_params error

### ISSUE THREAD

**Issue by vchu** [StanleyInnovation/vector_v1#29]
It looks like inside of the experimental gain tuning branch, [`vector_comm.py`](https://github.com/StanleyInnovation/vector_v1/blob/experimental_gain_tuning/vector_common/vector_ros/src/vector/vector_comm.py) changes the function call definition to `_update_move_base_params`

Specifically it goes from: 
` def _update_move_base_params(self,config):` to  `def _update_move_base_params(self):`

This causes an error because this function subscribes to the topic `/move_base/DWAPlannerROS`. The exact line is:
 `rospy.Subscriber("/move_base/DWAPlannerROS/parameter_updates",Config,self._update_move_base_params)`. 
Since the 2nd argument is no longer in the definition for `_update_move_base_params`, ros throws an error:

`[ERROR] [WallTime: 1479937929.388957] bad callback: <bound method VectorDriver._update_move_base_params of <vector.vector_comm.VectorDriver instance at 0x7f0896ed9b00>>
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/topics.py", line 720, in _invoke_callback
    cb(msg)
TypeError: _update_move_base_params() takes exactly 1 argument (2 given)
`

What was the reason for removing the `config` argument? And what should be the fix? Remove the subscriber or add the argument back in.

**Comment by PatrickHussey** [comment]
The argument was accidentally removed should be (self,config). I can update it if you want.

**Comment by vchu** [comment]
Got it, thanks! I can go ahead and update it. no worries!

**Comment by vchu** [comment]
For some reason when doing the formal merge into the master the problem went away. Maybe when I merged the first time into a branch, I did it wrong.

Anyways, closing since this isn't an issue anymore.
