### ISSUE TITLE
Differences in robot model

### ISSUE THREAD

**Issue by dekent** [StanleyInnovation/vector_v1#8]
I've been using the jaco 2 urdf provided in vector_v1 with some of our old jaco code, and I noticed that it's different from the robot model from the vector_dev repository.  We're planning to update some of our old jaco code and would like more information before jumping in to urdf adjustments.  Could we get a summary of the robot model changes from vector_dev to vector_v1, and the rationale behind them?

Thanks!

**Comment by PeterMitrano** [comment]
@dekent is this fixed by #13 ?

**Comment by dekent** [comment]
Yep!
