### ISSUE TITLE
Left Back Wheel Jitter

### ISSUE THREAD

**Issue by banerjs** [StanleyInnovation/vector_v1#9]
Just came across this issue today where the left back wheel of the robot was jittering even though no joystick commands were given:

https://www.dropbox.com/sh/o1thk9p667zbwao/AADy0pLUbHnZ_WdqALBsmxyza?dl=0

There's a video of the problem as well as a bag file containing the all the /cmd_vel topics (only 2 of the topics were publishing any messages)

**Comment by PatrickHussey** [comment]
New release is in the experimental branch now.
